version: '3.9'

services:
  tickets:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: ${CONTAINER_REGISTRY}/tickets:${TAG}
    container_name: tickets-${TAG}
    restart: always
    environment:
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "8085:8080"
    volumes:
      - ./logs:/opt/app/logs
