version: '3.9'

services:
  surf:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: ${CONTAINER_REGISTRY}/surf:${TAG}
    container_name: surf
    restart: always
    environment:
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_TO: ${MAIL_TO}
      MAIL_BCC: ${MAIL_BCC}

    ports:
      - "8085:8080"
    volumes:
      - ./logs:/opt/app/logs
